### ISSUE TITLE
keep connection open

### ISSUE THREAD

**Issue by surfzoid** [mkorz/b618reboot#13]
Hi,
by default, request is configured "keep-a-live : true"
could you please either add at the end of the reboot 
'''
requests.session().close()
'''

or setup request
s = requests.session()
s.config['keep_alive'] = False

this will prevent error :already connected when using API with another script in parallel

**Comment by mkorz** [comment]
Hello,

Interesting ... have you tried adding it and did disabling keep-alive fixed this error for you? 

I would assume (this could be completely wrong) that router is just not smart enough to handle more than one admin authenticated session at the time and the error happens at the higher level.

I'm happy to add it if fixed things for you!

**Comment by surfzoid** [comment]
Yes i add it, i think about one thing, i hve same problem as you, so i use your scrip in a cron task, but not directly, i use a custom python script whose check the signal.
`#! /usr/bin/python
# -*- coding: utf-8 -*-
# Python v3 PyQt5
from huawei_lte_api.Client import Client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
from huawei_lte_api.Connection import Connection
connection = AuthorizedConnection('http://admin:pass@ip/')

client = Client(connection) 

dico=(client.monitoring.status())

quatreG="vas savoir!"
buchette="x"
for key, value in dico.items():
    #print(key, " : ", value)
    if key == "CurrentNetworkTypeEx" : quatreG=value
    if key == "SignalIcon" : buchette=value

if quatreG == "1011":
	print("On est en 4G+ : " + quatreG)
else :
	print("On est en 4G : " + quatreG)

print("nombre de buchettes: " + buchette)

print("Déconexion : " + client.user.logout())`

**Comment by surfzoid** [comment]
``

**Comment by mkorz** [comment]
Current master (https://github.com/mkorz/b618reboot/commit/b6d7d5b877e9d530424df9cde01e3e34c9fcbf82) should help then. It defaults to current behaviour (keep-alive is turned on), but this could be disabled via config setting.
